changelog:
    categories:
        - title: Breaking Changes
          labels:
              - breaking-change
        - title: Exciting New Features :tada
          labels:
              - enhancement
        - title: Bug fixes
          labels:
              - bug
        - title: Other
          labels:
              - '*'
