name: 'CI'

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x]

    name: Build with ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build

  lint:
    strategy:
      matrix:
        node-version: [18.x]

    name: Check style with ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: echo $ENV_FILE | base64 -d > .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci

      - name: Check commit message
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Check lint
        run: npm run lint

      - name: Check types
        run: npm run check-types

  test:
    strategy:
      matrix:
        node-version: [18.x]

    name: Run all tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo $ENV_FILE | base64 -d > .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci

      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests
        run: npm run test:integration
